paths:   
  /products:
    get:
      summary: Returns a list of products + total items.
      tags:
        - products  
      parameters:
        - in: query
          name: category
          schema:
            type: string
          description: category of products   
        - in: query
          name: page
          schema:
            type: number   
        - in: query
          name: limit
          schema:
            type: number  
      responses:
        "200":
          description: A list of products + total items
          content:
            application/json:
              schema:
                type: object
                properties:
                  products:
                    type: array
                    items:
                      $ref: "#/components/schemas/Product"
                  lastPage:
                    type: number
                    example: 2         
                  totalItems:
                    type: number
                    example: 15      
        "400":
          $ref: '#/components/responses/badRequest'      
            
    post:
      summary: Creates a new product
      tags:
        - products
      security: 
        - bearerAuth: []  
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                orderId:
                  type: string
                itemId:
                  type: string
                title:
                  type: string
                quantity:
                  type: string
                price:
                  type: string  
                category:
                  type: string  
                description:
                  type: string  
                maxQuantityAllowedInCart:
                  type: number
                images:
                  type: array
                  items:
                    type: string
                    format: binary    
          application/json:
            schema:
              type: object
              properties:
                orderId:
                  type: string
                  example: 65819aaa5cffe695be11eb20  
                itemId:
                  type: string
                  example: 65819aaa5cffe695be11eb21 
                productId:
                  type: string
                  example: 650b1ffc1882fc118a114d1b  
      responses:
        "201":
          description: Returns created product
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
        "400":
          $ref: '#/components/responses/badRequest'
        "401":
          $ref: '#/components/responses/unauthorized'
        "403":
          $ref: '#/components/responses/forbidden'  
        "404":
          description: if order not found / product not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error" 
                      
                              
  /products/{productId}:
    get:
      summary: Returns a single product.
      tags:
        - products 
      parameters:
        - in: path
          name: productId
          type: string
          required: true
          schema:
            type: string
            example: 650b1ed61882fc118a114d19
          description: The product ID
      responses:
        "200":
          description: returns a single product with its description
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Product"
        "400":
          $ref: '#/components/responses/badRequest'
        "404":
          description: returns an error with "Product Not Found!" message
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"

  /products/title:
    get:
      summary: Returns all products title.
      tags:
        - products 
      responses:
        "200":
          description: returns all products title
          content:
            application/json:
              schema:
                type: array
                items:
                  example: 'Modern Sofa'
  /products/count:
    get:
      summary: Returns all products count.
      tags:
        - products
      security: 
        - bearerAuth: []   
      responses:
        "200":
          description: returns all products count
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: number
                    example: 15 

  /products/category:
    get:
      summary: Returns all products categories.
      tags:
        - products
      responses:
        "200":
          description: returns all products categories
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
                example:
                - CHAIR
                - LAMP
                - TABLE 

  /products/search:
    get:
      summary: Returns all products whose title includes the given text 
      tags:
        - products
      parameters:
        - in: query
          name: searchTerm
          schema:
            type: string
            description: Search for given text in products title  
        - in: query
          name: category
          schema:
            type: string
          description: Search for given text in specified category of products   
        - in: query
          name: page
          schema:
            type: number   
        - in: query
          name: limit
          schema:
            type: number 
      responses:
        "200":
          description: Returns all products whose title includes the given text
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Product" 
