openapi: 3.0.0
info:
  title: API Documents
  description: API documentation for SoftLand
  version: 1.0.0
servers:
  - url: http://localhost:3000
    description: SoftLand server



components:
  responses:
    unauthorized:
        description: when authorization errors occur (jwt errors)
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
                  example: 'jwt message'
    forbidden:
        description: when user has valid token but can't access to this route due to his/her role
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
                  example: 'Access denied'
    badRequest:
      description: when user sends invalid request body or invalid object id
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'              

  securitySchemes:
    bearerAuth:     
      type: http
      scheme: bearer
      in: header
      bearerFormat: JWT 

  schemas:
    Product:
      type: object
      properties:
        _id:
          type: string
          example: 650b1ed61882fc118a114d19
        title:
          type: string
          example: Modern Sofa
        price:
          type: number
          example: 180
        category:
          type: string
          example: SOFA
        imageUrl:
          type: string
          example: images\products\11.png
        discount:
          type: number
          example: 0.2
        discountExpiration:
          type: string
          example: 2024-03-28T16:33:26.500Z
        __v:
          type: number
          example: 0

    Error:
      type: object
      properties:
        message:
          type: string
          example: error message

    Cart:
      type: object
      properties: 
        product: 
          $ref: "#/components/schemas/Product"
        quantity: 
          type: number
          example: 2
        _id:
          type: string
          example: 650b1ed61882fc118a114d19  

    Order:
      type: object
      properties: 
        _id: 
          type: string
          example: 650b1ed61882fc118a114d19
        user:
          oneOf: 
            - type: string
              example: 650b1ed61882fc118a114d19
            - type: object
              properties:
                _id: 
                  type: string
                  example: 650b1ed61882fc118a114d19      
                username: 
                  type: string
                  example: navid      
        items:
          type: array
          items:
            oneOf: 
              - type: object
                properties:
                  product:
                    $ref: "#/components/schemas/Product"
                  quantity:
                    type: number
                    example: 10  
              - type: object
                properties:
                  product:
                    type: object
                    properties:
                      productId:
                        type: string
                        example: 650b1ed61882fc118a114d19 
                      title:
                        type: string
                        example: Modern Sofa 
                      price:
                        type: number
                        example: 122.99 
                  quantity:
                    type: number
                    example: 10  
                  isInStock:
                    type: boolean
                    example: false
        discountPercentage:
          type: number
          example: 0.2              
        deliveryDate:
          type: string
          example: 2024-04-08


    User:
      type: object
      properties: 
        _id: 
          type: string
          example: 655769ef14b767ea9f0cfe6c
        username: 
          type: string
          example: "navid"
        role:
          type: string
          example: CUSTOMER
        phoneNumber:
          type: string
          example: "09336652515"
        email:
          type: string
          example: example@gmail.com
        birthDate:
          type: string
          example: 2010-04-06  
        address:
          type: string
          example: Tabriz, rajaee shahr  
        __v:
          type: number
          example: 2

    Review:
      type: object
      properties: 
        _id: 
          type: string
          example: 655769ef14b767ea9f0cfe6c
        product: 
          type: string
          example: 655769ef14b767ea9f0cfe6c
        user:
          oneOf: 
            - type: string
              example: 650b1ed61882fc118a114d19
            - type: object
              properties:
                _id: 
                  type: string
                  example: 650b1ed61882fc118a114d19      
                username: 
                  type: string
                  example: navid
        rating:
          type: number
          example: 5
        review:
          type: string
          example: perfect
        validationStatus:
          type: String
          example: PENDING
        createdAt:
          type: date
          example: 2024-03-28T16:33:26.500Z
        updatedAt:
          type: date
          example: 2024-03-28T16:33:26.500Z
        __v:
          type: number
          example: 2

    Tokens:
      type: object
      properties: 
        accessToken: 
          type: string
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiQ1VTVE9NRVIiLCJpYXQiOjE3MDA1OTc1NDMsImV4cCI6MTcwMDU5OTM0Mywic3ViIjoiNjU1NzY5ZWYxNGI3NjdlYTlmMGNmZTZjIn0.xukyt6wPXeXRZ9iS3m2ZCrO3EW3Fhmy7qDxMEyJ7xNs
        refreshToken: 
          type: string
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJyb2xlIjoiQ1VTVE9NRVIiLCJpYXQiOjE3MDA1OTc1NDMsImV4cCI6MTcwMDU5OTM0Mywic3ViIjoiNjU1NzY5ZWYxNGI3NjdlYTlmMGNmZTZjIn0.xukyt6wPXeXRZ9iS3m2ZCrO3EW3Fhmy7qDxMEyJ7xNs 

    Ticket:
      type: object
      properties: 
        customer: 
          type: string
          example: 650b1ed61882fc118a114d19
        topic:
          type: string
          example: topic  
        chat: 
          type: array
          items:
            type: object
            properties:
              role:
                type: string
                example: CUSTOMER
              chatText:
                type: string
                example: bla bla bla
              date:
                type: date
                example: 2024-03-28T16:33:26.500Z
        status:
          type: string
          example: OPEN



 